name: dbt_finance
version: "1.0.0"
config-version: 2
require-dbt-version: [">=1.11.0", "<2.0.0"]

profile: finance

model-paths:    ["models"]
macro-paths:    ["macros"]
target-path:    "target"
clean-targets:  ["target", "dbt_packages"]

models:
  dbt_finance:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["finance", "staging"]

    marts:
      +materialized: table
      +access: public
      +schema: marts
      +tags: ["finance", "marts"]
      +contract:
        enforced: true
      +grants:
        select: ['ANALYTICS_DEV_ROLE']

tests:
  dbt_finance:
    +severity: error
    +store_failures: true
    +schema: test_failures
